import { Category, DishSummary } from './types';

// A curated list of 100 items to ensure the user gets their "100 recipes" request immediately available to browse.
export const DISH_CATALOG: DishSummary[] = [
    // MAINS (ULAM) - MEAT
    { id: '1', name: 'Chicken Adobo', category: Category.MAINS, description: 'The unofficial national dish, braised in vinegar and soy sauce.' },
    { id: '2', name: 'Pork Sinigang', category: Category.SOUPS, description: 'Pork belly in a sour tamarind broth with vegetables.' },
    { id: '3', name: 'Kare-Kare', category: Category.MAINS, description: 'Oxtail and tripe stew in a thick savory peanut sauce.' },
    { id: '4', name: 'Lechon Kawali', category: Category.MAINS, description: 'Crispy deep-fried pork belly with liver sauce.' },
    { id: '5', name: 'Bicol Express', category: Category.MAINS, description: 'Pork stewed in coconut milk with lots of chili peppers.' },
    { id: '6', name: 'Sisig', category: Category.MAINS, description: 'Sizzling chopped pork face and ears, seasoned with calamansi and chili.' },
    { id: '7', name: 'Crispy Pata', category: Category.MAINS, description: 'Deep-fried pork leg served with soy-vinegar dip.' },
    { id: '8', name: 'Beef Kaldereta', category: Category.MAINS, description: 'Tomato-based beef stew with liver spread and peppers.' },
    { id: '9', name: 'Mechado', category: Category.MAINS, description: 'Beef stew larded with pork fat strips in tomato sauce.' },
    { id: '10', name: 'Dinuguan', category: Category.MAINS, description: 'Savory pork blood stew with vinegar and chili.' },
    { id: '11', name: 'Chicken Inasal', category: Category.MAINS, description: 'Grilled chicken marinated in lemongrass, calamansi, and annatto.' },
    { id: '12', name: 'Pininyahang Manok', category: Category.MAINS, description: 'Chicken stewed in milk/cream with pineapple chunks.' },
    { id: '13', name: 'Bistek Tagalog', category: Category.MAINS, description: 'Beef steak marinated in soy sauce and calamansi topped with onions.' },
    { id: '14', name: 'Embutido', category: Category.MAINS, description: 'Filipino-style meatloaf wrapped in foil and steamed.' },
    { id: '15', name: 'Lumpia Shanghai', category: Category.MAINS, description: 'Deep-fried spring rolls filled with minced pork.' },
    { id: '16', name: 'Pork Binagoongan', category: Category.MAINS, description: 'Pork stewed in shrimp paste (bagoong).' },
    { id: '17', name: 'Humba', category: Category.MAINS, description: 'Sweet braised pork belly, popular in the Visayas.' },
    { id: '18', name: 'Menudo', category: Category.MAINS, description: 'Pork and liver stew with potatoes, carrots, and raisins.' },
    { id: '19', name: 'Afritada', category: Category.MAINS, description: 'Chicken or pork stew in tomato sauce with vegetables.' },
    { id: '20', name: 'Pochero', category: Category.MAINS, description: 'Stew with pork/beef, plantains, and chickpeas.' },
    { id: '21', name: 'Daing na Bangus', category: Category.MAINS, description: 'Milkfish marinated in vinegar and garlic, then fried.' },
    { id: '22', name: 'Escabeche', category: Category.MAINS, description: 'Sweet and sour fish with ginger and peppers.' },
    { id: '23', name: 'Relyenong Bangus', category: Category.MAINS, description: 'Stuffed milkfish.' },
    { id: '24', name: 'Kinilaw', category: Category.MAINS, description: 'Raw fish cured in vinegar (Filipino ceviche).' },
    { id: '25', name: 'Inihaw na Liempo', category: Category.MAINS, description: 'Grilled pork belly strips.' },

    // SOUPS (SABAW)
    { id: '26', name: 'Bulalo', category: Category.SOUPS, description: 'Beef shank soup with bone marrow and corn.' },
    { id: '27', name: 'Tinola', category: Category.SOUPS, description: 'Chicken ginger soup with green papaya and chili leaves.' },
    { id: '28', name: 'Sinampalukang Manok', category: Category.SOUPS, description: 'Chicken sour soup using tamarind leaves.' },
    { id: '29', name: 'Nilagang Baka', category: Category.SOUPS, description: 'Boiled beef soup with cabbage and potatoes.' },
    { id: '30', name: 'Batchoy', category: Category.SOUPS, description: 'Noodle soup with pork offal, crushed pork cracklings, and egg.' },
    { id: '31', name: 'Sotanghon Soup', category: Category.SOUPS, description: 'Cellophane noodle soup with chicken.' },
    { id: '32', name: 'Papaitan', category: Category.SOUPS, description: 'Bitter goat innards soup.' },
    { id: '33', name: 'Kansi', category: Category.SOUPS, description: 'Ilonggo beef soup, a cross between Bulalo and Sinigang.' },
    { id: '34', name: 'Misua Soup', category: Category.SOUPS, description: 'Thin flour noodle soup with meatballs or patola.' },
    { id: '35', name: 'Pancit Molo', category: Category.SOUPS, description: 'Wonton soup originating from Molo, Iloilo.' },

    // VEGETABLES (GULAY)
    { id: '36', name: 'Pinakbet', category: Category.VEGETABLE, description: 'Mixed vegetables stewed in fish sauce or shrimp paste.' },
    { id: '37', name: 'Laing', category: Category.VEGETABLE, description: 'Dried taro leaves cooked in thick coconut milk and chili.' },
    { id: '38', name: 'Gising-Gising', category: Category.VEGETABLE, description: 'Spicy winged beans in coconut milk.' },
    { id: '39', name: 'Tortang Talong', category: Category.VEGETABLE, description: 'Eggplant omelet.' },
    { id: '40', name: 'Adobong Kangkong', category: Category.VEGETABLE, description: 'Water spinach sautéed in soy sauce, vinegar, and garlic.' },
    { id: '41', name: 'Ginataang Kalabasa at Sitaw', category: Category.VEGETABLE, description: 'Squash and string beans in coconut milk.' },
    { id: '42', name: 'Chopsuey', category: Category.VEGETABLE, description: 'Stir-fried mixed vegetables with meat.' },
    { id: '43', name: 'Monggo Guisado', category: Category.VEGETABLE, description: 'Sautéed mung bean stew, often served on Fridays.' },
    { id: '44', name: 'Lumpiang Sariwa', category: Category.VEGETABLE, description: 'Fresh spring rolls with peanut sauce.' },
    { id: '45', name: 'Ensaladang Talong', category: Category.VEGETABLE, description: 'Grilled eggplant salad with tomatoes and onions.' },

    // NOODLES (PANCIT)
    { id: '46', name: 'Pancit Canton', category: Category.NOODLES, description: 'Stir-fried wheat noodles with meat and vegetables.' },
    { id: '47', name: 'Pancit Bihon', category: Category.NOODLES, description: 'Thin rice noodles stir-fried with soy sauce and citrus.' },
    { id: '48', name: 'Pancit Palabok', category: Category.NOODLES, description: 'Rice noodles with shrimp gravy, tinapa flakes, and chicharon.' },
    { id: '49', name: 'Pancit Malabon', category: Category.NOODLES, description: 'Thick rice noodles with seafood sauce.' },
    { id: '50', name: 'Pancit Habhab', category: Category.NOODLES, description: 'Lucban noodles eaten directly from a banana leaf without utensils.' },
    { id: '51', name: 'Pancit Lomi', category: Category.NOODLES, description: 'Thick egg noodle soup with thickened broth.' },
    { id: '52', name: 'Spaghetti (Filipino Style)', category: Category.NOODLES, description: 'Sweet style spaghetti with hotdogs.' },

    // RICE (KANIN)
    { id: '53', name: 'Sinangag', category: Category.RICE, description: 'Garlic fried rice.' },
    { id: '54', name: 'Java Rice', category: Category.RICE, description: 'Yellow fried rice seasoned with turmeric.' },
    { id: '55', name: 'Bagoong Rice', category: Category.RICE, description: 'Fried rice flavored with shrimp paste and green mangoes.' },
    { id: '56', name: 'Arroz Valenciana', category: Category.RICE, description: 'Sticky rice with chicken, chorizo, and coconut milk.' },
    { id: '57', name: 'Bringhe', category: Category.RICE, description: 'Kapampangan paella made with sticky rice.' },
    { id: '58', name: 'Kiampong', category: Category.RICE, description: 'Salty fried rice popular in Binondo.' },

    // BREAKFAST (SILOG)
    { id: '59', name: 'Tapsilog', category: Category.BREAKFAST, description: 'Cured beef, fried rice, and egg.' },
    { id: '60', name: 'Longsilog', category: Category.BREAKFAST, description: 'Sweet or spicy sausage, fried rice, and egg.' },
    { id: '61', name: 'Tocilog', category: Category.BREAKFAST, description: 'Sweet cured pork, fried rice, and egg.' },
    { id: '62', name: 'Bangsilog', category: Category.BREAKFAST, description: 'Milkfish, fried rice, and egg.' },
    { id: '63', name: 'Corned Beef Silog', category: Category.BREAKFAST, description: 'Sautéed corned beef, fried rice, and egg.' },
    { id: '64', name: 'Champorado', category: Category.BREAKFAST, description: 'Sweet chocolate rice porridge, often eaten with tuyo.' },
    { id: '65', name: 'Arroz Caldo', category: Category.BREAKFAST, description: 'Chicken rice porridge with ginger.' },
    { id: '66', name: 'Goto', category: Category.BREAKFAST, description: 'Rice porridge with ox tripe.' },
    { id: '67', name: 'Pandesal', category: Category.BREAKFAST, description: 'The quintessential Filipino bread roll.' },
    { id: '68', name: 'Taho', category: Category.BREAKFAST, description: 'Silken tofu with arnibal (syrup) and sago pearls.' },

    // STREET FOOD
    { id: '69', name: 'Isaw', category: Category.STREET_FOOD, description: 'Grilled chicken or pork intestines.' },
    { id: '70', name: 'Betamax', category: Category.STREET_FOOD, description: 'Grilled coagulated chicken blood blocks.' },
    { id: '71', name: 'Adidas', category: Category.STREET_FOOD, description: 'Grilled chicken feet.' },
    { id: '72', name: 'Kwek-Kwek', category: Category.STREET_FOOD, description: 'Quail eggs coated in orange batter and fried.' },
    { id: '73', name: 'Fishballs', category: Category.STREET_FOOD, description: 'Flat balls made of pulverized fish meat.' },
    { id: '74', name: 'Squidballs', category: Category.STREET_FOOD, description: 'Fried balls of squid meat.' },
    { id: '75', name: 'Balut', category: Category.STREET_FOOD, description: 'Fertilized duck egg embryo.' },
    { id: '76', name: 'Turon', category: Category.STREET_FOOD, description: 'Deep-fried banana roll with jackfruit and sugar.' },
    { id: '77', name: 'Banana Cue', category: Category.STREET_FOOD, description: 'Deep-fried bananas coated in caramelized sugar.' },
    { id: '78', name: 'Camote Cue', category: Category.STREET_FOOD, description: 'Deep-fried sweet potatoes coated in caramelized sugar.' },
    { id: '79', name: 'Sorbetes', category: Category.STREET_FOOD, description: 'Dirty ice cream served in buns or cones.' },
    { id: '80', name: 'Carioca', category: Category.STREET_FOOD, description: 'Chewy glutinous rice balls dipped in sugar glaze.' },

    // DESSERT (PANGHIMAGAS)
    { id: '81', name: 'Halo-Halo', category: Category.DESSERT, description: 'Shaved ice with mixed fruits, beans, and evaporated milk.' },
    { id: '82', name: 'Leche Flan', category: Category.DESSERT, description: 'Rich creme caramel custard.' },
    { id: '83', name: 'Ube Halaya', category: Category.DESSERT, description: 'Purple yam jam.' },
    { id: '84', name: 'Biko', category: Category.DESSERT, description: 'Sweet sticky rice cake with coconut curds (latik).' },
    { id: '85', name: 'Bibingka', category: Category.DESSERT, description: 'Rice cake cooked in clay pots lined with banana leaves.' },
    { id: '86', name: 'Puto', category: Category.DESSERT, description: 'Steamed rice cakes.' },
    { id: '87', name: 'Kutsinta', category: Category.DESSERT, description: 'Brown sticky rice cake served with grated coconut.' },
    { id: '88', name: 'Sapin-Sapin', category: Category.DESSERT, description: 'Layered glutinous rice and coconut dessert.' },
    { id: '89', name: 'Maja Blanca', category: Category.DESSERT, description: 'Coconut pudding with corn kernels.' },
    { id: '90', name: 'Buko Pandan', category: Category.DESSERT, description: 'Young coconut strips and jelly in cream.' },
    { id: '91', name: 'Fruit Salad', category: Category.DESSERT, description: 'Canned fruit cocktail with cream and condensed milk.' },
    { id: '92', name: 'Cassava Cake', category: Category.DESSERT, description: 'Cake made from grated cassava root and coconut milk.' },
    { id: '93', name: 'Palitaw', category: Category.DESSERT, description: 'Boiled rice cake coated in sesame seeds, sugar, and coconut.' },
    { id: '94', name: 'Suman', category: Category.DESSERT, description: 'Glutinous rice cake wrapped in banana or palm leaves.' },
    { id: '95', name: 'Ginataan Bilo-Bilo', category: Category.DESSERT, description: 'Glutinous rice balls in coconut milk.' },
    { id: '96', name: 'Minatamis na Saging', category: Category.DESSERT, description: 'Bananas cooked in sweet syrup.' },
    { id: '97', name: 'Buko Pie', category: Category.DESSERT, description: 'Young coconut custard pie.' },
    { id: '98', name: 'Polvoron', category: Category.DESSERT, description: 'Crumbly shortbread made of toasted flour and powdered milk.' },
    { id: '99', name: 'Pastillas de Leche', category: Category.DESSERT, description: 'Sweet milk candies.' },
    { id: '100', name: 'Yema', category: Category.DESSERT, description: 'Sweet custard candy.' },
];
